export const BLITZ = [
  [
    { name: 'GOLFARIA: Collect 2 clubs', types: ['golfaria'] },
    { name: 'ATTACTICS: Reach Corporal in ranked mode (Rank 30)', types: ['attactics'] },
    { name: 'PILOT QUEST: Collect 3 Zoldnaks', types: ['pilotquest'] },
    {
      name: 'BUSHIDO BALL: Beat round 1 with 3 different characters (solo)',
      types: ['bushidoball'],
    },
    { name: "AVIANOS: Create 20 units with Quetzal's Muster", types: ['avianos'] },
    { name: 'OVERBOLD: Complete round 7', types: ['overbold'] },
    { name: 'DIVERS: Obtain any Lance weapon', types: ['divers'] },
    { name: 'MORTOL II: Collect 5 keys', types: ['mortol2'] },
    { name: 'PARTY HOUSE: Max out popularity and cash at the same time', types: ['partyhouse'] },
    { name: 'HYPER CONTENDER: Win Round 4 of the Tournament', types: ['hypercontender'] },
    {
      name: 'Have an exact 50 of anything in 8 games (points, score, and in-game timers count too)',
      types: ['general'],
    },
  ],
  [
    { name: 'THE BIG BELL RACE: Win 3 different courses without dying', types: ['bigbellrace'] },
    {
      name: "NIGHT MANOR: Have 10 different items (multiple journal entries doesn't count)",
      types: ['nightmanor'],
    },
    { name: 'STAR WASPIR: Clear wave 1 with the Yellow Ship', types: ['starwaspir'] },
    { name: 'LORDS OF DISKONIA: Win a Quick Battle on Squire difficulty', types: ['diskonia'] },
    { name: 'QUIBBLE RACE: Have $1000+', types: ['quibblerace'] },
    { name: 'CYBER OWLS: Clear Chicago', types: ['cyberowls'] },
    { name: 'WALDORF’S JOURNEY: Read 5 signs', types: ['waldorfsjourney'] },
    { name: 'PLANET ZOLDATH: Eat 7 slabs of meat', types: ['planetzoldath'] },
    { name: 'MAGIC GARDEN: Obtain a score multiplier of 4x', types: ['magicgarden'] },
    { name: 'BARBUTA: Die to the Red Phantom (Small Map Square)', types: ['barbuta'] },
    { name: 'Jump in 8 games', types: ['general'] },
  ],

  [
    { name: 'MORTOL: Clear 1-A', types: ['mortol'] },
    { name: 'CAMPANELLA 3: Clear 2 waves 0%', types: ['camp3'] },
    { name: 'PORGY: Collect 3 fuel tanks', types: ['porgy'] },
    { name: 'ROCK ON! ISLAND: Beat Initial Encounter', types: ['rockonisland'] },
    { name: 'NINPEK: Kill 7 enemies while dead in one playthrough', types: ['ninpek'] },
    { name: 'VELGRESS: Buy 5 items from shops', types: ['velgress'] },
    { name: 'CAMPANELLA 2: Clear Burrows II', types: ['camp2'] },
    { name: 'BUG HUNTER: Have 3 energy end up on the same tile', types: ['bughunter'] },
    { name: 'CAMPANELLA: Defeat the Stage B Boss', types: ['camp'] },
    { name: 'HOT FOOT: Win a game using Draft mode', types: ['hotfoot'] },
    { name: 'Collect 5 gifts for the garden', types: ['general'] },
  ],

  [
    { name: 'FIST HELL: Get money by collecting food at full health', types: ['fisthell'] },
    {
      name: 'ONION DELIVERY: Deliver 8 onions in a single day and complete the day',
      types: ['oniondelivery'],
    },
    { name: 'ELFAZAR’S HAT: Earn a continue in the bonus round', types: ['elfazarshat'] },
    { name: 'WARPTANK: Collect a coffee (must beat level with it)', types: ['warptank'] },
    { name: 'VALBRACE: Level up at a throne', types: ['valbrace'] },
    { name: 'BLOCK KOALA: Beat 2 story levels as Koalarana (Pink Koala)', types: ['blockkoala'] },
    { name: 'GRIMSTONE: Defeat 15 enemies', types: ['grimstone'] },
    { name: 'PAINT CHASE: Beat 6 levels', types: ['paintchase'] },
    { name: 'PINGOLF: Score par or less on 4 courses', types: ['pingolf'] },
    { name: 'CARAMEL CARAMEL: Snap 8 bonus background elements', types: ['caramelcaramel'] },
    { name: 'BARBUTA: Free tile, click first to claim', types: ['general'] },
  ],

  [
    { name: 'DEVILITION: Beat Round 4', types: ['devilition'] },
    { name: 'MINI & MAX: Talk to 20 NPCs', types: ['miniandmax'] },
    { name: 'COMBATANTS: Vanquish 20 total Red Ants', types: ['combatants'] },
    {
      name: 'RAIL HEIST: Beat a level while bringing back a money crate intact',
      types: ['railheist'],
    },
    { name: 'VAINGER: Read 10 different terminals', types: ['vainger'] },
    { name: 'RAKSHASA: Beat the first stage', types: ['rakshasa'] },
    { name: 'SEASIDE DRIVE: Clear Stage 1', types: ['seasidedrive'] },
    { name: 'CAMOUFLAGE: Get eaten by Frog, Gator, & Bird', types: ['camouflage'] },
    { name: 'KICK CLUB: Score 25,000 points', types: ['kickclub'] },
    { name: 'MOONCAT: Use a warp (hidden near flowers)', types: ['mooncat'] },
    { name: 'Die in 10 different games', types: ['general'] },
  ],

  [
    { name: 'MOONCAT: Defeat 5 unique enemy types', types: ['mooncat'] },
    { name: 'BUG HUNTER: Buy 7 different modules', types: ['bughunter'] },
    { name: 'WARPTANK: Beat 6 levels', types: ['warptank'] },
    { name: 'PORGY: Collect the Buster Torpedos', types: ['porgy'] },
    { name: 'ROCK ON! ISLAND: Use CLUB-PASS; beat Crossroads', types: ['rockonisland'] },
    { name: 'MORTOL: Clear 2-B using OPEN-TOMB', types: ['mortol'] },
    { name: 'ELFAZAR’S HAT: Clear the first stage', types: ['elfazarshat'] },
    { name: 'BUSHIDO BALL: Beat round 3 with default settings', types: ['bushidoball'] },
    { name: 'QUIBBLE RACE: Train a Quibble to have 70+ speed', types: ['quibblerace'] },
    { name: 'CYBER OWLS: Clear Hong Kong', types: ['cyberowls'] },
    { name: 'Increase your max HP in 3 games', types: ['general'] },
  ],

  [
    { name: 'DIVERS: Kill a Slime Eel', types: ['divers'] },
    { name: 'BLOCK KOALA: Beat 5 story levels', types: ['blockkoala'] },
    { name: 'CAMPANELLA: Collect 5 hidden coffees', types: ['camp'] },
    { name: 'BARBUTA: Collect 300 gold', types: ['barbuta'] },
    { name: 'CAMPANELLA 3: Beat Robopoke (Stage B)', types: ['camp3'] },
    { name: 'CARAMEL CARAMEL: Beat the Cookie or the Egg', types: ['caramelcaramel'] },
    { name: 'STAR WASPIR: Clear wave 1 with the Red Ship', types: ['starwaspir'] },
    { name: 'LORDS OF DISKONIA: Win the first story mission', types: ['diskonia'] },
    { name: 'MAGIC GARDEN: Save 10+ Oppies at once twice', types: ['magicgarden'] },
    { name: 'PILOT QUEST: Plant 4 seeds at the crash site', types: ['pilotquest'] },
    { name: 'Collect 2 gold disks', types: ['general'] },
  ],

  [
    { name: 'GRIMSTONE: Talk to the Angel Zad in Mission Francesco (south)', types: ['grimstone'] },
    { name: 'MINI & MAX: Stand on the hanging lamp in the upper right', types: ['miniandmax'] },
    { name: 'ATTACTICS: Have at least 10 Grunts in formation', types: ['attactics'] },
    {
      name: 'ONION DELIVERY: Deliver 20 onions total (can be different runs)',
      types: ['oniondelivery'],
    },
    {
      name: 'PINGOLF: Be in first place in the standings immediately after hole 9',
      types: ['pingolf'],
    },
    { name: 'VALBRACE: Clear Floor 1', types: ['valbrace'] },
    { name: 'THE BIG BELL RACE: Gold disk', types: ['bigbellrace'] },
    { name: 'AVIANOS: Max out blessings from one Ancestor', types: ['avianos'] },
    {
      name: 'SEASIDE DRIVE: Clear Stage 1 without your shot charging down to gray',
      types: ['seasidedrive'],
    },
    { name: 'WALDORF’S JOURNEY: Reach at least 50%', types: ['waldorfsjourney'] },
    { name: 'Buy an item from a shop in 5 different games', types: ['general'] },
  ],

  [
    { name: 'KICK CLUB: Beat Racket World', types: ['kickclub'] },
    { name: 'FIST HELL: Survive 6 waves in the gym (left of start)', types: ['fisthell'] },
    {
      name: 'HYPER CONTENDER: Win a tournament fight with 5 different characters',
      types: ['hypercontender'],
    },
    {
      name: 'MORTOL II: In one run, defeat at least 2 enemies with each player class',
      types: ['mortol2'],
    },
    { name: 'PAINT CHASE: Get 30+ points from a single level', types: ['paintchase'] },
    { name: 'HOT FOOT: Use 7 Special Throws or Abilities', types: ['hotfoot'] },
    { name: 'CAMPANELLA 2: Have 300 coins', types: ['camp2'] },
    { name: 'CAMOUFLAGE: Collect 8 oranges', types: ['camouflage'] },
    { name: 'VELGRESS: Hold 40 coins at once', types: ['velgress'] },
    { name: 'RAKSHASA: Beat the Bridge Demon', types: ['rakshasa'] },
    { name: 'Collect a cherry disk', types: ['general'] },
  ],

  [
    { name: 'NINPEK: Break 5 spike blocks', types: ['ninpek'] },
    { name: 'DEVILITION: Have 4 villagers at once', types: ['devilition'] },
    { name: 'NIGHT MANOR: Gold disk', types: ['nightmanor'] },
    { name: 'VAINGER: Visit Latom Sector (via the top left corner)', types: ['vainger'] },
    { name: 'PARTY HOUSE: Get busted by the fire department', types: ['partyhouse'] },
    {
      name: 'PLANET ZOLDATH: Max out health by collecting 4 energy cubes',
      types: ['planetzoldath'],
    },
    { name: 'RAIL HEIST: Beat 5 levels', types: ['railheist'] },
    { name: 'COMBATANTS: Have an army of 5+ NPC Soldier Ants', types: ['combatants'] },
    { name: 'OVERBOLD: Buy a price hiked item', types: ['overbold'] },
    { name: 'GOLFARIA: Hit 5 birdies or eagles', types: ['golfaria'] },
    { name: 'Find an easter egg UFO', types: ['general'] },
  ],

  [
    { name: 'SEASIDE DRIVE: Reach 50,000+ points', types: ['seasidedrive'] },
    { name: 'RAIL HEIST: Use LAZY-COPS; Beat Root Around & Sitting Ducks', types: ['railheist'] },
    { name: 'DEVILITION: Beat the first round in under a minute', types: ['devilition'] },
    { name: 'AVIANOS: Win a Hatchling game', types: ['avianos'] },
    { name: 'HYPER CONTENDER: Beat Draft Mode (Default settings)', types: ['hypercontender'] },
    {
      name: 'PLANET ZOLDATH: Gather 4 tools on the floor of the same screen',
      types: ['planetzoldath'],
    },
    { name: 'DIVERS: Purchase Godblood', types: ['divers'] },
    { name: 'CAMPANELLA 2: Clear Moire Woods I or Rink I', types: ['camp2'] },
    { name: 'CAMPANELLA: Defeat the Stage A Boss', types: ['camp'] },
    { name: 'WALDORF’S JOURNEY: Use four unique items in one run', types: ['waldorfsjourney'] },
    { name: 'Find an egg in 4 games', types: ['general'] },
  ],

  [
    { name: 'PAINT CHASE: Get an extra life by getting 120+ points', types: ['paintchase'] },
    { name: 'BUG HUNTER: End 2 days with 0 bugs alive', types: ['bughunter'] },
    { name: 'ONION DELIVERY: Complete day 1', types: ['oniondelivery'] },
    { name: "WARPTANK: Change your Warptank's color", types: ['warptank'] },
    { name: 'FIST HELL: Clear the first scare', types: ['fisthell'] },
    { name: 'MORTOL: Get 5 lives by killing enemies', types: ['mortol'] },
    { name: 'CAMOUFLAGE: Save 4 babies', types: ['camouflage'] },
    {
      name: 'BLOCK KOALA: Using WORM-1234, clear any level numbered 30 or higher',
      types: ['blockkoala'],
    },
    { name: 'CYBER OWLS: Clear any 2 Rescue Missions using GETM-EOUT', types: ['cyberowls'] },
    { name: 'PORGY: Collect 3 torpedo upgrades', types: ['porgy'] },
    { name: 'Defeat 3 bosses', types: ['general'] },
  ],

  [
    { name: "MOONCAT: Cross the wizard's bridge (main path)", types: ['mooncat'] },
    { name: 'PINGOLF: Slam dunk the ball into the hole on 6 courses', types: ['pingolf'] },
    { name: 'NINPEK: Eat 3 sandwiches', types: ['ninpek'] },
    {
      name: "CARAMEL CARAMEL: Get hurt and heal by snapping a red enemy's pic",
      types: ['caramelcaramel'],
    },
    { name: 'VAINGER: Visit Verde Sector (via either bottom corner', types: ['vainger'] },
    { name: 'RAKSHASA: Revive yourself 4 times in one run', types: ['rakshasa'] },
    { name: 'ELFAZAR’S HAT: Have three level 2 upgrades active at once', types: ['elfazarshat'] },
    { name: 'BARBUTA: Fill 4 item slots (you start at 1)', types: ['barbuta'] },
    { name: 'KICK CLUB: Eat 3 hidden desserts', types: ['kickclub'] },
    { name: 'MORTOL II: Unlock 3 doors', types: ['mortol2'] },
    { name: 'Defeat a boss in 3 different games', types: ['general'] },
  ],

  [
    { name: 'PILOT QUEST: Open a chest', types: ['pilotquest'] },
    {
      name: 'NIGHT MANOR: Collect a gem (Diamond, Topaz, Ruby, or Emerald)',
      types: ['nightmanor'],
    },
    { name: 'THE BIG BELL RACE: Get 40 points', types: ['bigbellrace'] },
    { name: 'GOLFARIA: Rescue 2 green balls', types: ['golfaria'] },
    { name: 'HOT FOOT: Make the coach stop you from stalling by hoarding', types: ['hotfoot'] },
    { name: 'VELGRESS: Bounce on the giant squid', types: ['velgress'] },
    { name: 'CAMPANELLA 3: Beat Galbrain (Stage A)', types: ['camp3'] },
    { name: 'ATTACTICS: Have 5 promoted units alive at once', types: ['attactics'] },
    { name: 'COMBATANTS: Let a Blue Queen Ant die', types: ['combatants'] },
    { name: 'VALBRACE: Buy something from the crone', types: ['valbrace'] },
    { name: 'Collect a food item in 3 different games', types: ['general'] },
  ],

  [
    { name: 'GRIMSTONE: Reach Level 3 with any character', types: ['grimstone'] },
    { name: 'MAGIC GARDEN: Save 100 Oppies in a run', types: ['magicgarden'] },
    { name: 'OVERBOLD: Buy 7 different upgrades in one run', types: ['overbold'] },
    {
      name: 'BUSHIDO BALL: Score a point with a 3-point charged special attack',
      types: ['bushidoball'],
    },
    { name: 'MINI & MAX: Collect any 4 upgrades', types: ['miniandmax'] },
    { name: 'STAR WASPIR: Clear wave 2', types: ['starwaspir'] },
    { name: 'QUIBBLE RACE: Gold disk', types: ['quibblerace'] },
    { name: 'PARTY HOUSE: Have 6 trouble in your party at once', types: ['partyhouse'] },
    { name: 'LORDS OF DISKONIA: Have 25+ gold', types: ['diskonia'] },
    { name: 'ROCK ON! ISLAND: Use CLUB-PASS; beat Oasis', types: ['rockonisland'] },
    { name: 'Collect a beverage in 3 different games', types: ['general'] },
  ],

  [
    { name: 'PARTY HOUSE: Beat a scenario', types: ['partyhouse'] },
    { name: 'WALDORF’S JOURNEY: Collect 3 puffins in one run', types: ['waldorfsjourney'] },
    { name: "MINI & MAX: Cure Max's fleas", types: ['miniandmax'] },
    { name: 'ONION DELIVERY: Complete day 2', types: ['oniondelivery'] },
    { name: 'RAKSHASA: Score 10,000', types: ['rakshasa'] },
    { name: 'COMBATANTS: Beat ‘First Blood’', types: ['combatants'] },
    { name: 'ELFAZAR’S HAT: Beat the tree stump miniboss', types: ['elfazarshat'] },
    { name: 'BUG HUNTER: Kill 5 bugs using non-attack modules', types: ['bughunter'] },
    { name: 'BARBUTA: Kill 10 enemies', types: ['barbuta'] },
    { name: 'HYPER CONTENDER: Win a fight using code PAST-RULE', types: ['hypercontender'] },
    { name: 'Enter a top 5 score on 3 arcade leaderboards', types: ['general'] },
  ],

  [
    { name: 'PLANET ZOLDATH: Collect a Map Piece', types: ['planetzoldath'] },
    { name: 'PILOT QUEST: Have 5 Moon Ingots', types: ['pilotquest'] },
    { name: 'RAIL HEIST: Collect 6 badges', types: ['railheist'] },
    {
      name: 'CAMPANELLA 2: Obtain 3 different upgrades in one run (squares in the top left)',
      types: ['camp2'],
    },
    {
      name: 'QUIBBLE RACE: Bet for your sponsored Quibble and win the round',
      types: ['quibblerace'],
    },
    { name: 'CAMOUFLAGE: Beat Oasis (Level 9)', types: ['camouflage'] },
    { name: 'MOONCAT: Visit 10 different rooms', types: ['mooncat'] },
    { name: 'WARPTANK: Beat Orb Sector', types: ['warptank'] },
    { name: 'BLOCK KOALA: Make and beat a custom level', types: ['blockkoala'] },
    { name: "AVIANOS: Kill 10 units with Tri-lock's lightning", types: ['avianos'] },
    { name: 'Enter a top 3 score on an arcade leaderboard', types: ['general'] },
  ],

  [
    { name: 'ATTACTICS: Beat 8 levels', types: ['attactics'] },
    {
      name: 'PAINT CHASE: Activate the same power-up tile 3 times in one life (by repainting it)',
      types: ['paintchase'],
    },
    { name: 'OVERBOLD: Complete a wave with $500+ stakes', types: ['overbold'] },
    { name: 'NIGHT MANOR: Successfully hide from the killer', types: ['nightmanor'] },
    { name: 'GRIMSTONE: Put money in the bank in Santonio (north)', types: ['grimstone'] },
    { name: 'GOLFARIA: Destroy 2 parbots', types: ['golfaria'] },
    { name: 'BUSHIDO BALL: Beat round 2 on Hyper Speed', types: ['bushidoball'] },
    { name: 'VELGRESS: Use 5 jump pads', types: ['velgress'] },
    { name: 'PORGY: Retrieve the Missiles from the lower right caves', types: ['porgy'] },
    { name: 'PINGOLF: Gold disk', types: ['pingolf'] },
    { name: 'Enter a name on 5 arcade leaderboards', types: ['general'] },
  ],

  [
    { name: 'DEVILITION: Kill 4 demons with one piece', types: ['devilition'] },
    { name: 'HOT FOOT: Win 3 games in a row', types: ['hotfoot'] },
    { name: 'VAINGER: Collect 2 shield upgrades', types: ['vainger'] },
    { name: 'NINPEK: Score 5,000+ points', types: ['ninpek'] },
    { name: 'CYBER OWLS: Clear Congo', types: ['cyberowls'] },
    { name: 'LORDS OF DISKONIA: Make an enemy disk drown', types: ['diskonia'] },
    { name: 'CARAMEL CARAMEL: Score 20,000 points', types: ['caramelcaramel'] },
    { name: 'FIST HELL: Have $30 at once', types: ['fisthell'] },
    { name: 'MORTOL: Use LEAF-HEAD, turn 5 enemies into vines', types: ['mortol'] },
    { name: 'VALBRACE: Defeat the crone (steal from her)', types: ['valbrace'] },
    { name: 'Beat 1 level/scenario in 3 different epic play games', types: ['general'] },
  ],

  [
    { name: 'CAMPANELLA: Have 10 lives', types: ['camp'] },
    { name: 'KICK CLUB: Eat 7 hot dogs', types: ['kickclub'] },
    {
      name: 'THE BIG BELL RACE: Finish a race while an opponent has 3+ laps left',
      types: ['bigbellrace'],
    },
    { name: 'MORTOL II: Activate a switch', types: ['mortol2'] },
    { name: 'CAMPANELLA 3: Win the bonus game', types: ['camp3'] },
    { name: 'MAGIC GARDEN: Reach a score of 10,000+', types: ['magicgarden'] },
    { name: 'ROCK ON! ISLAND: Have 15 chickens at once in a main level', types: ['rockonisland'] },
    { name: 'STAR WASPIR: Have a 10x multiplier', types: ['starwaspir'] },
    { name: 'DIVERS: Bring back any Pearl', types: ['divers'] },
    { name: 'SEASIDE DRIVE: Clear Stage 2', types: ['seasidedrive'] },
    { name: 'Go underwater in 3 different games', types: ['general'] },
  ],

  [
    { name: 'ONION DELIVERY: Heal 8 HP without dying', types: ['oniondelivery'] },
    { name: 'PORGY: Return 3 fish eggs to their mother', types: ['porgy'] },
    {
      name: 'MORTOL II: Defeat the Cyclops Minotaur miniboss (straight right from the start)',
      types: ['mortol2'],
    },
    { name: 'MOONCAT: Beat an underwater level', types: ['mooncat'] },
    { name: 'COMBATANTS: Beat ‘Skirmish’', types: ['combatants'] },
    {
      name: 'ROCK ON! ISLAND: Have all 10 different cavemen built at once in a main level',
      types: ['rockonisland'],
    },
    { name: 'LORDS OF DISKONIA: Win a Quick Battle on Knight difficulty', types: ['diskonia'] },
    {
      name: 'KICK CLUB: Beat 3 levels without picking up the ball (using headbonks and slides)',
      types: ['kickclub'],
    },
    { name: 'PILOT QUEST: Have 50 Moon Drops in the Wild Zone', types: ['pilotquest'] },
    { name: 'CYBER OWLS: Clear Moscow', types: ['cyberowls'] },
    { name: 'Fall into a (non-water) pit in 3 different games', types: ['general'] },
  ],

  [
    {
      name: 'HYPER CONTENDER: Win 3 tournament fights in in a row with no rematches',
      types: ['hypercontender'],
    },
    { name: 'HOT FOOT: Get a blowout', types: ['hotfoot'] },
    { name: 'MORTOL: End a level with 30 or more lives', types: ['mortol'] },
    { name: 'CAMPANELLA 2: Upgrade your max health or max fuel', types: ['camp2'] },
    { name: 'THE BIG BELL RACE: Collect each of the 5 different powerups', types: ['bigbellrace'] },
    { name: 'BARBUTA: Visit at least 25 rooms', types: ['barbuta'] },
    { name: 'FIST HELL: Clear 2nd Scare', types: ['fisthell'] },
    { name: 'VELGRESS: Collect 2 keys in a single run', types: ['velgress'] },
    { name: 'NINPEK: Collect some coffee in a bonus area', types: ['ninpek'] },
    {
      name: 'PAINT CHASE: Complete a level that has power-up tiles without using any of them',
      types: ['paintchase'],
    },
    { name: 'Kill an enemy in 12 different games', types: ['general'] },
  ],

  [
    { name: 'DEVILITION: Have 3 of the same piece to choose from', types: ['devilition'] },
    { name: 'PINGOLF: Destroy 8 orange obstacles', types: ['pingolf'] },
    { name: 'QUIBBLE RACE: Watch 2 Quibbles die', types: ['quibblerace'] },
    { name: 'ELFAZAR’S HAT: Kill 3 enemies using bombs', types: ['elfazarshat'] },
    { name: 'WARPTANK: Complete the three levels in the initial hub room', types: ['warptank'] },
    { name: 'CARAMEL CARAMEL: Score 5,000 points in the prologue', types: ['caramelcaramel'] },
    { name: 'MAGIC GARDEN: Kill 4 mushrooms', types: ['magicgarden'] },
    { name: 'BUG HUNTER: Complete your first job', types: ['bughunter'] },
    { name: 'BLOCK KOALA: Make 3 different blocks into metal 5 blocks', types: ['blockkoala'] },
    { name: 'ATTACTICS: Score 500+ points in Survival Mode', types: ['attactics'] },
    { name: 'See a bird in 3 different games', types: ['general'] },
  ],

  [
    { name: 'NIGHT MANOR: Find 5 journal entries', types: ['nightmanor'] },
    { name: 'MINI & MAX: Rid the books of Silverfish', types: ['miniandmax'] },
    { name: 'SEASIDE DRIVE: Clear a stage deathless', types: ['seasidedrive'] },
    { name: 'PLANET ZOLDATH: Trade with an NPC', types: ['planetzoldath'] },
    { name: 'WALDORF’S JOURNEY: Open a chest', types: ['waldorfsjourney'] },
    { name: 'VALBRACE: Give the Red Knight 3 items', types: ['valbrace'] },
    { name: 'PARTY HOUSE: Get any guest to 9 popularity', types: ['partyhouse'] },
    {
      name: 'OVERBOLD: Achieve max health, through health upgrades or medkits',
      types: ['overbold'],
    },
    { name: 'VAINGER: Recharge at 5 different checkpoints', types: ['vainger'] },
    { name: 'GRIMSTONE: Learn 3 Skills', types: ['grimstone'] },
    { name: 'Crash a vehicle in 4 different games', types: ['general'] },
  ],

  [
    { name: 'CAMPANELLA 3: Clear 2 waves 100%', types: ['camp3'] },
    { name: 'BUSHIDO BALL: Win a 2P tournament', types: ['bushidoball'] },
    { name: 'GOLFARIA: Obtain the Brakes', types: ['golfaria'] },
    { name: 'RAKSHASA: Use each of the three weapon types in one run', types: ['rakshasa'] },
    { name: 'STAR WASPIR: Clear Wave 1 with the Gray Ship', types: ['starwaspir'] },
    { name: 'DIVERS: Level up a Diver', types: ['divers'] },
    { name: 'CAMPANELLA: Score 15,000 points', types: ['camp'] },
    { name: 'RAIL HEIST: Kill a chicken', types: ['railheist'] },
    { name: 'CAMOUFLAGE: Reach 50% completion or more', types: ['camouflage'] },
    { name: 'AVIANOS: Enter combat with extra reserves (>40 units)', types: ['avianos'] },
    { name: 'Get an extra life in 3 different games', types: ['general'] },
  ],
] as const;
