export const CAMPANELLA3 = [
  [
    { name: 'DODGE: Score 100+', types: ['dodge'] },
    { name: 'DODGE: Score 150+', types: ['dodge'] },
    { name: 'DODGE2: Score 50+', types: ['dodge2'] },
    { name: 'DODGE2: Score 100+', types: ['dodge2'] },
  ],
  [
    { name: 'BRICKS: Destroy 3 gold blocks in one run', types: ['bricks'] },
    { name: 'BRICKS: Score 15+', types: ['bricks'] },
    { name: 'JUGGLE: Score 60+', types: ['juggle'] },
    { name: 'JUGGLE: Score 120+', types: ['juggle'] },
  ],
  [
    { name: 'BIRD: Score 20+', types: ['bird'] },
    { name: 'BIRD: Score 40+', types: ['bird'] },
    { name: 'STEP: Score 160+', types: ['step'] },
    { name: 'STEP: Score 220+', types: ['step'] },
  ],
  [
    { name: 'SWORD: Score 100+', types: ['sword'] },
    { name: 'SWORD: Score 150+', types: ['sword'] },
    { name: 'SWORD2: Score 100+', types: ['sword2'] },
    { name: 'SWORD2: Destroy half of the yellow barriers', types: ['sword2'] },
  ],
  [
    { name: 'MINES: Score 25+', types: ['mines'] },
    { name: 'MINES: Score 50+', types: ['mines'] },
    { name: 'TELEMI: Score 40+', types: ['telemi'] },
    { name: 'TELEMI: Score 70+', types: ['telemi'] },
  ],
  [
    { name: 'SKATER: Score 30+', types: ['skater'] },
    { name: 'SKATER: Score 50+', types: ['skater'] },
    { name: 'RACING: Score 25+', types: ['racing'] },
    { name: 'RACING: Score 35+', types: ['racing'] },
  ],
  [
    { name: 'BOSS: Break 4 yellow blocks', types: ['boss'] },
    { name: 'BOSS2: Destroy the 4 red barriers that protect the orb', types: ['boss2'] },
  ],
  [
    { name: 'SNIPER: Score 15+', types: ['sniper'] },
    { name: 'SNIPER: Score 30+', types: ['sniper'] },
    { name: 'BATS: Score 100+', types: ['bats'] },
    { name: 'BATS: Score 150+', types: ['bats'] },
  ],
  [
    { name: 'DROPS: Score 10+', types: ['drops'] },
    { name: 'DROPS: Score 20+', types: ['drops'] },
    { name: 'STRIKE: Score 100+', types: ['strike'] },
    { name: 'STRIKE: Get 3 strikes before bouncing', types: ['strike'] },
  ],
  [
    { name: 'MELT: Score 300+', types: ['melt'] },
    { name: 'MELT: Melt all of the bricks', types: ['melt'] },
    { name: 'RUNGUN: Score 60+', types: ['rungun'] },
    { name: 'RUNGUN: Score 100+', types: ['rungun'] },
  ],
  [
    { name: 'POOL: Score 50+', types: ['pool'] },
    { name: 'POOL: Score 80+', types: ['pool'] },
    { name: 'WANTED: Score 40+', types: ['wanted'] },
    { name: 'WANTED: Score 60+', types: ['wanted'] },
  ],
  [
    { name: 'MASHIT: Score 75+', types: ['mashit'] },
    { name: 'MASHIT: Score 100+', types: ['mashit'] },
    { name: 'OBEY: Score 50+', types: ['obey'] },
    { name: 'OBEY: Score 75+', types: ['obey'] },
  ],
  [
    { name: 'HOPPER: Score 50+', types: ['hopper'] },
    { name: 'HOPPER: Score 80+', types: ['hopper'] },
    { name: 'BOUNCY: Score 300+', types: ['bouncy'] },
    { name: 'BOUNCY: Catch 5 yellow rocks in a row', types: ['bouncy'] },
    { name: 'PLATS: Score 100+', types: ['plats'] },
    { name: 'PLATS: Score 200+', types: ['plats'] },
  ],
  [
    { name: 'PUSHEM: Score 80+', types: ['pushem'] },
    { name: 'PUSHEM: Soft lock the game', types: ['pushem'] },
    { name: 'ARENA: Score 20+', types: ['pushem'] },
    { name: 'ARENA: Score 40+', types: ['pushem'] },
  ],
  [
    { name: 'TUNNEL: Score 40+', types: ['tunnel'] },
    { name: 'TUNNEL: Score 40+', types: ['tunnel'] },
    { name: 'CROWD: Score 50+', types: ['crowd'] },
    { name: 'CROWD: Score 75+', types: ['crowd'] },
  ],
  [
    { name: 'DUEL: Score 50+', types: ['duel'] },
    { name: 'DUEL: Score 70+', types: ['duel'] },
    { name: 'WEEDS: Score 60+', types: ['WEEDS'] },
    { name: 'WEEDS: Score 100+', types: ['WEEDS'] },
  ],
  [
    { name: 'FIND: Score 250+', types: ['find'] },
    { name: 'FIND: Find the face on a first reveal', types: ['find'] },
    { name: 'HEARTS: Score 80+', types: ['hearts'] },
    { name: 'HEARTS: Reveal 10 hearts in a row', types: ['hearts'] },
  ],
  [
    { name: 'BOPPER: Score 50+', types: ['bopper'] },
    { name: 'BOPPER: Score 80+', types: ['bopper'] },
    { name: 'TURRET: Score 50+', types: ['turret'] },
    { name: 'TURRET: Score 100+', types: ['turret'] },
  ],
  [
    { name: 'STOPEM: Score 50+', types: ['stopem'] },
    { name: 'STOPEM: Score 100+', types: ['stopem'] },
    { name: 'DEFEND: Score 40+', types: ['defend'] },
    { name: 'DEFEND: Score 60+', types: ['defend'] },
  ],
  [
    { name: 'TELEPO: Score 20+', types: ['telepo'] },
    { name: 'TELEPO: Score 40+', types: ['telepo'] },
    { name: 'CHERRY: Score 90+', types: ['cherry'] },
    { name: 'CHERRY: Score 130+', types: ['cherry'] },
  ],
  [
    { name: 'MORE?: Score 60+', types: ['more?'] },
    { name: 'MORE?: Score 100+', types: ['more?'] },
    { name: 'ALIENS: Score 75+', types: ['aliens'] },
    { name: 'ALIENS: Score 100+', types: ['aliens'] },
  ],
  [
    { name: 'COINS: Score 69+', types: ['coins'] },
    { name: 'COINS: Score 123+', types: ['coins'] },
    { name: 'MIMIC: Score 60+', types: ['mimic'] },
    { name: 'MIMIC: Score 100+', types: ['mimic'] },
  ],
  [
    { name: 'FISHIN: Score 12+', types: ['fishin'] },
    { name: 'FISHIN: Catch a red fish', types: ['fishin'] },
    { name: 'SEARCH: Score 50+', types: ['search'] },
    { name: 'SEARCH: Score 70+', types: ['search'] },
  ],
  [
    { name: 'EYESPY: Score 150+', types: ['eyespy'] },
    { name: 'EYESPY: Collect 4 apples before the eyes opens twice', types: ['eyespy'] },
    { name: 'MUGS: Score 80+', types: ['mugs'] },
    { name: 'MUGS: Score 130+', types: ['mugs'] },
  ],
  [
    { name: 'Reach a total score of 10,000+', types: ['general'] },
    { name: 'Have a total score containing 420', types: ['general'] },
    { name: 'Have a total score containing 69', types: ['general'] },
    { name: 'Defeat Galbrain', types: ['general'] },
  ],
] as const;
