export const STANDARD = [
  [
    { name: 'BARBUTA: Collect the reward from a green skull', types: ['barbuta', 'easy'] },
    { name: 'BARBUTA: Speak to 3 different Bean NPCs', types: ['barbuta', 'easy'] },
    {
      name: 'BUG HUNTER: Get 4 kills in one job by pushing bugs into pits',
      types: ['bughunter', 'easy'],
    },
    { name: 'BUG HUNTER: Get 3 kills with one module use', types: ['bughunter', 'easy'] },
    {
      name: 'MAGIC GARDEN: Use OVER-GROW; save 30+ oppies in a run',
      types: ['magicgarden', 'easy'],
    },
    {
      name: 'MAGIC GARDEN: Defeat an enemy worth at least 500 points',
      types: ['magicgarden', 'easy'],
    },
    { name: 'MORTOL: Earn six 1-ups by killing enemies', types: ['mortol', 'easy'] },
    { name: 'MORTOL: Beat 2 levels without killing any enemies', types: ['mortol', 'easy'] },
    {
      name: 'KICK CLUB: Beat Racket World without using uncharged kicks',
      types: ['kickclub', 'easy'],
    },
    { name: 'KICK CLUB: Score 50,000+ points', types: ['kickclub', 'easy'] },
    {
      name: 'FIST HELL: Clear the first scare and enter the shop with $20 or more',
      types: ['fisthell', 'easy'],
    },
    { name: 'FIST HELL: Survive 6 waves in the gym as Cat', types: ['fisthell', 'easy'] },
    { name: 'CAMPANELLA 2: Defeat Rotondo at end of Burrows II', types: ['campanella2', 'easy'] },
    { name: 'CAMPANELLA 2: Have 300 coins', types: ['campanella2', 'easy'] },
    { name: 'VALBRACE: Defeat the crone', types: ['valbrace', 'easy'] },
    { name: 'VALBRACE: Give the Red Knight 5 items', types: ['valbrace', 'easy'] },
    {
      name: 'RAKSHASA: Score 1000+ points with each of the three weapon types in one run',
      types: ['rakshasa', 'easy'],
    },
    { name: 'RAKSHASA: Have 0 skulls by using bell pickups', types: ['rakshasa', 'easy'] },
    { name: 'CYBER OWLS: Have 3 extra lives at once', types: ['cyberowls', 'easy'] },
    { name: 'CYBER OWLS: Clear Hong Kong only destroying Road Toad', types: ['cyberowls', 'easy'] },
  ],
  [
    { name: 'VELGRESS: Clear out a shop’s stock', types: ['velgress', 'easy'] },
    { name: 'VELGRESS: Hold 50 coins at once', types: ['velgress', 'easy'] },
    {
      name: 'DEVILITION: Beat 3 rounds while placing the maximum number of pieces each round',
      types: ['devilition', 'easy'],
    },
    { name: 'DEVILITION: Beat 5 rounds in one run', types: ['devilition', 'easy'] },
    { name: 'MOONCAT: Use 2 warps', types: ['mooncat', 'easy'] },
    {
      name: 'MOONCAT: Beat 8 rooms in a row without dying or using warps',
      types: ['mooncat', 'easy'],
    },
    { name: 'CAMOUFLAGE: Get eaten by a Frog, Gator, & Bird', types: ['camouflage', 'easy'] },
    { name: 'CAMOUFLAGE: Collect 10 oranges', types: ['camouflage', 'easy'] },
    { name: 'AVIANOS: Max out blessings from one Ancestor', types: ['avianos', 'easy'] },
    { name: 'AVIANOS: Control 15+ tiles at once', types: ['avianos', 'easy'] },
    {
      name: 'ONION DELIVERY: Deliver 8 onions in a single day and complete the day',
      types: ['oniondelivery', 'easy'],
    },
    { name: 'ONION DELIVERY: Deliver 10 onions in a single day', types: ['oniondelivery', 'easy'] },
    { name: 'VAINGER: Collect 5 items', types: ['vainger', 'easy'] },
    { name: 'VAINGER: Defeat a boss', types: ['vainger', 'easy'] },
    { name: 'LORDS OF DISKONIA: Win a Quick Battle', types: ['lordsofdiskonia', 'easy'] },
    { name: 'LORDS OF DISKONIA: Win the first mission', types: ['lordsofdiskonia', 'easy'] },
    { name: 'ELFAZAR’S HAT: Earn a continue in the bonus round', types: ['elfazarshat', 'easy'] },
    {
      name: 'ELFAZAR’S HAT: Have three level 2 upgrades active at once',
      types: ['elfazarshat', 'easy'],
    },
    { name: 'PILOT QUEST: Plant 4 seeds at the crash site', types: ['pilotquest', 'easy'] },
    { name: 'PILOT QUEST: Make a friend at the crash site', types: ['pilotquest', 'easy'] },
  ],
  [
    { name: 'ATTACTICS: Win 5 battles without losing any flags', types: ['attactics', 'easy'] },
    {
      name: 'ATTACTICS: Have 3 Heroes at once (Ranked or Survival Mode)',
      types: ['attactics', 'easy'],
    },
    {
      name: 'BUSHIDO BALL: Win 3 matches in a tournament without using charge shots (default options)',
      types: ['bushidoball', 'easy'],
    },
    {
      name: 'BUSHIDO BALL: Win 3 matches in a tournament on Fast speed (other options default)',
      types: ['bushidoball', 'easy'],
    },
    {
      name: 'BLOCK KOALA: Beat 3 story levels without using the undo button',
      types: ['blockkoala', 'easy'],
    },
    { name: 'BLOCK KOALA: Beat 5 story levels', types: ['blockkoala', 'easy'] },
    { name: 'WALDORF’S JOURNEY: Read 5 signs', types: ['waldorfsjourney', 'easy'] },
    { name: 'WALDORF’S JOURNEY: Have 35 shells at once', types: ['waldorfsjourney', 'easy'] },
    { name: 'PARTY HOUSE: Get a Climber to 9 popularity', types: ['partyhouse', 'easy'] },
    { name: 'PARTY HOUSE: Have 6 trouble in a party at once', types: ['partyhouse', 'easy'] },
    {
      name: 'HOT FOOT: Use TEST-BAGS: Win a 30-point, 1-special-cost game. All throws that score points must be Special Throws',
      types: ['hotfoot', 'easy'],
    },
    {
      name: 'HOT FOOT: Win the first match three times with 6 unique characters',
      types: ['hotfoot', 'easy'],
    },
    { name: 'DIVERS: Open the chest containing the Parasite Hammer', types: ['divers', 'easy'] },
    { name: 'DIVERS: Reach level 3', types: ['divers', 'easy'] },
    {
      name: 'MORTOL II: In one run, kill 6 chickens without using the Bomber',
      types: ['mortolii', 'easy'],
    },
    { name: 'MORTOL II: Activate all the switches', types: ['mortolii', 'easy'] },
    {
      name: 'STAR WASPIR: Complete wave 1 without attacking the boss',
      types: ['starwaspir', 'easy'],
    },
    {
      name: 'STAR WASPIR: Beat wave 1 with 1500+ points (before bonus points) without touching any letters',
      types: ['starwaspir', 'easy'],
    },
    { name: 'SEASIDE DRIVE: Win the bonus game', types: ['seasidedrive', 'easy'] },
    {
      name: 'SEASIDE DRIVE: Clear Stage 1 with 3 lives and exactly 10,000 points (defeat only the boss)',
      types: ['seasidedrive', 'easy'],
    },
  ],
  [
    { name: 'NINPEK: Eat 5 sandwiches', types: ['ninpek', 'easy'] },
    {
      name: 'NINPEK: Collect 5 200-point drops (purple eggs) from enemies',
      types: ['ninpek', 'easy'],
    },
    { name: 'CAMPANELLA: Collect 5 coffees', types: ['campanella', 'easy'] },
    { name: 'CAMPANELLA: Use BEAN-DRIP; score 6,000+ points', types: ['campanella', 'easy'] },
    { name: 'GOLFARIA: Hit 3 eagles', types: ['golfaria', 'easy'] },
    { name: 'GOLFARIA: Destroy 3 parbots', types: ['golfaria', 'easy'] },
    {
      name: 'THE BIG BELL RACE: KO an opponent with 3 unique power-ups',
      types: ['thebigbellrace', 'easy'],
    },
    { name: 'THE BIG BELL RACE: Win Race 1 without boosters', types: ['thebigbellrace', 'easy'] },
    { name: 'PORGY: Collect 3 fuel tanks', types: ['porgy', 'easy'] },
    { name: 'PORGY: Collect the Buster Torpedos', types: ['porgy', 'easy'] },
    {
      name: 'ROCK ON! ISLAND: Have all 6 fully upgraded cavemen types at once',
      types: ['rockonisland', 'easy'],
    },
    {
      name: 'ROCK ON! ISLAND: Beat Initial Encounter without cavemen',
      types: ['rockonisland', 'easy'],
    },
    { name: 'PINGOLF: Destroy 10 orange obstacles', types: ['pingolf', 'easy'] },
    {
      name: 'PINGOLF: Par or better on 5 courses, dunking every stroke',
      types: ['pingolf', 'easy'],
    },
    {
      name: 'NIGHT MANOR: Successfully complete the hiding minigame twice',
      types: ['nightmanor', 'easy'],
    },
    { name: 'NIGHT MANOR: Find 10 journal entries', types: ['nightmanor', 'easy'] },
    { name: 'MINI & MAX: Rid the books of Silverfish', types: ['miniandmax', 'easy'] },
    { name: 'MINI & MAX: Slay the Water Bear in the west pot', types: ['miniandmax', 'easy'] },
    {
      name: 'QUIBBLE RACE: Bet against your sponsored Quibble and win the round',
      types: ['quibblerace', 'easy'],
    },
    {
      name: 'QUIBBLE RACE: Have your sponsored Quibble win the race, while boosting a different one',
      types: ['quibblerace', 'easy'],
    },
  ],
  [
    {
      name: 'PAINT CHASE: Win without destroying any airplanes in Course 3',
      types: ['paintchase', 'easy'],
    },
    {
      name: 'PAINT CHASE: EVEN-COAT allowed; beat courses 16, 17, and 20 while destroying all spike mines',
      types: ['paintchase', 'easy'],
    },
    {
      name: 'PLANET ZOLDATH: Drop 4 items at your ship in one run',
      types: ['planetzoldath', 'easy'],
    },
    {
      name: 'PLANET ZOLDATH: Max out health by collecting 4 energy cubes',
      types: ['planetzoldath', 'easy'],
    },
    { name: 'WARPTANK: Beat 3 sectors without killing any enemies', types: ['warptank', 'easy'] },
    {
      name: 'WARPTANK: Beat 3 sectors, defeating all possible enemies in each',
      types: ['warptank', 'easy'],
    },
    {
      name: 'CARAMEL CARAMEL: Score 8,000+ points in the prologue',
      types: ['caramelcaramel', 'easy'],
    },
    {
      name: 'CARAMEL CARAMEL: Snap 10 bonus background elements',
      types: ['caramelcaramel', 'easy'],
    },
    { name: 'RAIL HEIST: Beat 5 levels', types: ['railheist', 'easy'] },
    {
      name: 'RAIL HEIST: LAZY-COPS allowed; beat Root Around while destroying every barrel',
      types: ['railheist', 'easy'],
    },
    { name: 'OVERBOLD: Purchase 3 price hiked items in one run', types: ['overbold', 'easy'] },
    { name: 'OVERBOLD: Max out four upgrades at once', types: ['overbold', 'easy'] },
    {
      name: 'HYPER CONTENDER: Win 4 fights in one tournament on default ring settings',
      types: ['hypercontender', 'easy'],
    },
    {
      name: 'HYPER CONTENDER: Use PAST-RULE; beat Draft Mode twice',
      types: ['hypercontender', 'easy'],
    },
    { name: 'GRIMSTONE: Defeat 15 enemies', types: ['grimstone', 'easy'] },
    {
      name: 'GRIMSTONE: Get Rufus to level 2 and feed him a Dog Treat',
      types: ['grimstone', 'easy'],
    },
    { name: 'COMBATANTS: Beat ‘First Blood’ without shooting', types: ['combatants', 'easy'] },
    { name: 'COMBATANTS: Beat ‘Skirmish’ with no casualties', types: ['combatants', 'easy'] },
    { name: 'CAMPANELLA 3: Beat Galbrain', types: ['campanella3', 'easy'] },
    { name: 'CAMPANELLA 3: Win the bonus game', types: ['campanella3', 'easy'] },
  ],
  [
    { name: 'BARBUTA: Fill 5 item slots (you start at 1)', types: ['barbuta', 'medium'] },
    { name: 'BARBUTA: Obtain the Rod and Blood Sword', types: ['barbuta', 'medium'] },
    { name: 'NINPEK: Have 6 extra lives at once', types: ['ninpek', 'medium'] },
    { name: 'NINPEK: Collect a coffee without ever firing a shot', types: ['ninpek', 'medium'] },
    {
      name: 'AVIANOS: Win a Custom game with 8 Mountains (change no other settings)',
      types: ['avianos', 'medium'],
    },
    {
      name: 'AVIANOS: Win the campaign Hatchling game without using any miracles',
      types: ['avianos', 'medium'],
    },
    {
      name: 'THE BIG BELL RACE: Win a race, KOing each opponent at least once',
      types: ['thebigbellrace', 'medium'],
    },
    {
      name: 'THE BIG BELL RACE: Win 3 different races without collecting power-ups',
      types: ['thebigbellrace', 'medium'],
    },
    { name: 'HOT FOOT: Win 2 games in a row without jumping', types: ['hotfoot', 'medium'] },
    { name: 'HOT FOOT: Win 4 games in a row in one tournament', types: ['hotfoot', 'medium'] },
    { name: 'FIST HELL: Beat the 2nd scare', types: ['fisthell', 'medium'] },
    { name: 'FIST HELL: Have $50 at once', types: ['fisthell', 'medium'] },
    { name: 'ELFAZAR’S HAT: Clear Stage 1 without dying', types: ['elfazarshat', 'medium'] },
    {
      name: 'ELFAZAR’S HAT: Clear stages 1 and 2 without any upgrades or healing',
      types: ['elfazarshat', 'medium'],
    },
  ],
  [
    { name: 'BUG HUNTER: Buy 3 4-cost modules in one job', types: ['bughunter', 'medium'] },
    { name: 'BUG HUNTER: Complete your first job', types: ['bughunter', 'medium'] },
    {
      name: 'VELGRESS: Defeat all enemies in level 1 using your blaster',
      types: ['velgress', 'medium'],
    },
    { name: 'VELGRESS: Step on every bomb block in level 2', types: ['velgress', 'medium'] },
    { name: 'CAMOUFLAGE: Gold disk', types: ['camouflage', 'medium'] },
    { name: 'CAMOUFLAGE: Save 5 babies', types: ['camouflage', 'medium'] },
    { name: 'PORGY: Reach the Abyss (lowest depth area)', types: ['porgy', 'medium'] },
    { name: 'PORGY: Collect 4 torpedo upgrades', types: ['porgy', 'medium'] },
    {
      name: 'HYPER CONTENDER: Beat Draft Mode (Default settings)',
      types: ['hypercontender', 'medium'],
    },
    {
      name: 'HYPER CONTENDER: Use PAST-RULE; beat Tournament Mode (Default settings)',
      types: ['hypercontender', 'medium'],
    },
    { name: 'LORDS OF DISKONIA: Have 50+ gold', types: ['lordsofdiskonia', 'medium'] },
    {
      name: 'LORDS OF DISKONIA: Destroy 2+ enemy disks in one move',
      types: ['lordsofdiskonia', 'medium'],
    },
    { name: 'CYBER OWLS: Complete 2 non-rescue missions', types: ['cyberowls', 'medium'] },
    {
      name: 'CYBER OWLS: GETM-EOUT allowed; rescue each owl in the mini-game',
      types: ['cyberowls', 'medium'],
    },
  ],
  [
    { name: 'PAINT CHASE: Beat 6 courses', types: ['paintchase', 'medium'] },
    {
      name: 'PAINT CHASE: Beat 5 different courses with no enemies remaining',
      types: ['paintchase', 'medium'],
    },
    { name: 'PLANET ZOLDATH: Have 2 of each resource at once', types: ['planetzoldath', 'medium'] },
    {
      name: 'PLANET ZOLDATH: Collect the overworld ground Map Piece',
      types: ['planetzoldath', 'medium'],
    },
    {
      name: 'WARPTANK: Beat Orb Sector without destroying any floating eyeballs',
      types: ['warptank', 'medium'],
    },
    { name: 'WARPTANK: Beat Healing Sector', types: ['warptank', 'medium'] },
    {
      name: 'PARTY HOUSE: Beat a random scenario having purchased the maximum number of Old Friends and Rich Pals',
      types: ['partyhouse', 'medium'],
    },
    {
      name: 'PARTY HOUSE: Have 4 Celebrities in a party at once without getting busted',
      types: ['partyhouse', 'medium'],
    },
    {
      name: 'OVERBOLD: Complete a wave with $1000+ stakes without using bombs',
      types: ['overbold', 'medium'],
    },
    {
      name: 'OVERBOLD: Complete a wave with $800+ stakes without shooting',
      types: ['overbold', 'medium'],
    },
    { name: 'NIGHT MANOR: Gold disk', types: ['nightmanor', 'medium'] },
    { name: 'NIGHT MANOR: Collect the diamond', types: ['nightmanor', 'medium'] },
    {
      name: 'MINI & MAX: Return the stolen Termite Egg to the outlet',
      types: ['miniandmax', 'medium'],
    },
    {
      name: 'MINI & MAX: Save the brainwashed mouse near the portrait',
      types: ['miniandmax', 'medium'],
    },
  ],
  [
    {
      name: 'MAGIC GARDEN: Reach a score of 10,000+ before saving 50 Oppies',
      types: ['magicgarden', 'medium'],
    },
    { name: 'MAGIC GARDEN: Defeat 6 mushrooms in one combo', types: ['magicgarden', 'medium'] },
    { name: 'MORTOL: Clear all levels in World 1', types: ['mortol', 'medium'] },
    { name: 'MORTOL: Have 50+ Lives (No BENS-MODE)', types: ['mortol', 'medium'] },
    { name: 'GOLFARIA: Obtain the Block Buster', types: ['golfaria', 'medium'] },
    { name: 'GOLFARIA: Collect 3 clubs', types: ['golfaria', 'medium'] },
    { name: 'PINGOLF: Under par on 5 courses', types: ['pingolf', 'medium'] },
    { name: 'PINGOLF: Be in first place immediately after hole 9', types: ['pingolf', 'medium'] },
    { name: 'STAR WASPIR: Have a 30x multiplier', types: ['starwaspir', 'medium'] },
    { name: 'STAR WASPIR: Score 50,000+ points', types: ['starwaspir', 'medium'] },
    { name: 'COMBATANTS: Beat ‘Surprise!’', types: ['combatants', 'medium'] },
    { name: 'COMBATANTS: Beat ‘Pincered’', types: ['combatants', 'medium'] },
    { name: 'SEASIDE DRIVE: Beat Stage 2', types: ['seasidedrive', 'medium'] },
    { name: 'SEASIDE DRIVE: Destroy the UFO in Stage 3', types: ['seasidedrive', 'medium'] },
  ],
  [
    { name: 'ATTACTICS: Beat 8 levels in Campaign Mode', types: ['attactics', 'medium'] },
    { name: 'ATTACTICS: Reach Lieutenant (50+) in Ranked Mode', types: ['attactics', 'medium'] },
    { name: 'CAMPANELLA: Defeat the Stage B Boss', types: ['campanella', 'medium'] },
    { name: 'CAMPANELLA: Score 20,000+ points', types: ['campanella', 'medium'] },
    {
      name: 'WALDORF’S JOURNEY: Kill 3 squids in three different ways',
      types: ['waldorfsjourney', 'medium'],
    },
    {
      name: 'WALDORF’S JOURNEY: Purchase four unique items in one run',
      types: ['waldorfsjourney', 'medium'],
    },
    { name: 'DIVERS: Kill a Slime Eel', types: ['divers', 'medium'] },
    { name: 'DIVERS: Purchase Godblood', types: ['divers', 'medium'] },
    {
      name: 'RAKSHASA: Beat the green bridge mini-boss by arriving w/ 4+ skulls',
      types: ['rakshasa', 'medium'],
    },
    { name: 'RAKSHASA: Beat the first stage', types: ['rakshasa', 'medium'] },
    {
      name: 'PILOT QUEST: Defeat Big Borlg (large alien in the central ruins)',
      types: ['pilotquest', 'medium'],
    },
    { name: 'PILOT QUEST: Defeat Unktomi (Spider boss)', types: ['pilotquest', 'medium'] },
    { name: 'QUIBBLE RACE: WILD-BETS allowed; have $25,000', types: ['quibblerace', 'medium'] },
    { name: 'QUIBBLE RACE: Win 5 bets', types: ['quibblerace', 'medium'] },
  ],
  [
    { name: 'DEVILITION: Have 6 villagers at once', types: ['devilition', 'medium'] },
    {
      name: 'DEVILITION: Beat 5 rounds, placing only the middle piece of the available 3',
      types: ['devilition', 'medium'],
    },
    {
      name: 'BLOCK KOALA: WORM-1234 allowed; beat 3 eastern levels (41-49)',
      types: ['blockkoala', 'medium'],
    },
    {
      name: 'BLOCK KOALA: WORM-1234 allowed; beat 5 hedge maze levels (28-40)',
      types: ['blockkoala', 'medium'],
    },
    {
      name: 'ONION DELIVERY: Complete a day of deliveries driving only in reverse',
      types: ['oniondelivery', 'medium'],
    },
    { name: 'ONION DELIVERY: Complete 2 days of deliveries', types: ['oniondelivery', 'medium'] },
    { name: 'CARAMEL CARAMEL: Beat the Egg', types: ['caramelcaramel', 'medium'] },
    {
      name: 'CARAMEL CARAMEL: TEST-LENS allowed; defeat Dino Lord in Dino Planet',
      types: ['caramelcaramel', 'medium'],
    },
    {
      name: 'RAIL HEIST: Beat 4 levels while bringing back a money crate intact',
      types: ['railheist', 'medium'],
    },
    {
      name: 'RAIL HEIST: GOOD-SPUR allowed; beat Fowl Business with all chickens and lawmen killed',
      types: ['railheist', 'medium'],
    },
    { name: 'CAMPANELLA 2: Obtain the Friendship Bracelet', types: ['campanella2', 'medium'] },
    { name: 'CAMPANELLA 2: Obtain the Talisman (Cross) item', types: ['campanella2', 'medium'] },
    { name: 'GRIMSTONE: Have 3 Skills learned at once', types: ['grimstone', 'medium'] },
    { name: 'GRIMSTONE: Collect the money from the burned house', types: ['grimstone', 'medium'] },
  ],
  [
    { name: 'KICK CLUB: Eat 10 hidden desserts', types: ['kickclub', 'medium'] },
    { name: 'KICK CLUB: Beat Track World', types: ['kickclub', 'medium'] },
    { name: 'MOONCAT: Spawn 3 different sets of egg blocks', types: ['mooncat', 'medium'] },
    { name: 'MOONCAT: Defeat 6 unique enemy types', types: ['mooncat', 'medium'] },
    {
      name: 'BUSHIDO BALL: Win a 16-point match on Hyper speed (other options default)',
      types: ['bushidoball', 'medium'],
    },
    {
      name: 'BUSHIDO BALL: Win a 16-point match on Hyper speed (other options default)',
      types: ['bushidoball', 'medium'],
    },
    {
      name: 'ROCK ON! ISLAND: CLUB-PASS allowed; beat Terror Overhead',
      types: ['rockonisland', 'medium'],
    },
    {
      name: 'ROCK ON! ISLAND: CLUB-PASS allowed; beat Jungle Rush',
      types: ['rockonisland', 'medium'],
    },
    { name: 'VAINGER: Collect a Keycode from a major boss', types: ['vainger', 'medium'] },
    { name: 'VAINGER: Beat 3 bosses', types: ['vainger', 'medium'] },
    { name: 'MORTOL II: Gold disk', types: ['mortolii', 'medium'] },
    { name: 'MORTOL II: In one run, get eaten by all 4 worms', types: ['mortolii', 'medium'] },
    { name: 'VALBRACE: Level up at a throne', types: ['valbrace', 'medium'] },
    { name: 'VALBRACE: Clear Floor 1', types: ['valbrace', 'medium'] },
    { name: 'CAMPANELLA 3: Clear 6 waves 100%', types: ['campanella3', 'medium'] },
    { name: 'CAMPANELLA 3: Beat Robopoke (Stage B Boss)', types: ['campanella3', 'medium'] },
  ],
  [
    { name: 'BARBUTA: Visit at least 25 rooms', types: ['barbuta', 'hard'] },
    { name: 'BARBUTA: Defeat the Mimic', types: ['barbuta', 'hard'] },
    {
      name: 'PAINT CHASE: Beat 7 levels without using power-ups (boosting allowed)',
      types: ['paintchase', 'hard'],
    },
    { name: 'PAINT CHASE: Reach a score of 180+', types: ['paintchase', 'hard'] },
    {
      name: 'DEVILITION: Clear the screen of demons with at least 18 pieces remaining',
      types: ['devilition', 'hard'],
    },
    {
      name: 'DEVILITION: Beat 5 rounds, destroying all demons and humans every round',
      types: ['devilition', 'hard'],
    },
    { name: 'WALDORF’S JOURNEY: Cherry disk', types: ['waldorfsjourney', 'hard'] },
    { name: 'WALDORF’S JOURNEY: Have four puffins at once', types: ['waldorfsjourney', 'hard'] },
    { name: 'CARAMEL CARAMEL: Score 50,000+ points', types: ['caramelcaramel', 'hard'] },
    {
      name: 'CARAMEL CARAMEL: TEST-LENS allowed; beat Ghost Planet without using the camera before the boss',
      types: ['caramelcaramel', 'hard'],
    },
    {
      name: 'FIST HELL: In one life, have 4 different enemy types die by falling into pits',
      types: ['fisthell', 'hard'],
    },
    { name: 'FIST HELL: Survive 9 waves in the gym', types: ['fisthell', 'hard'] },
    {
      name: 'NIGHT MANOR: Successfully complete the hiding minigame in five different rooms',
      types: ['nightmanor', 'hard'],
    },
    {
      name: 'NIGHT MANOR: Successfully complete the hiding minigame in five different rooms',
      types: ['nightmanor', 'hard'],
    },
    { name: 'SEASIDE DRIVE: Reach 200,000+ points', types: ['seasidedrive', 'hard'] },
    { name: 'SEASIDE DRIVE: Use WEAK-SHOT; beat stage 2', types: ['seasidedrive', 'hard'] },
  ],
  [
    { name: 'BUG HUNTER: Complete a job with your energy maxed out', types: ['bughunter', 'hard'] },
    { name: 'BUG HUNTER: Use WORK-LESS; complete Job 7', types: ['bughunter', 'hard'] },
    { name: 'MORTOL: OPEN-TOMB allowed; clear all world 2 levels', types: ['mortol', 'hard'] },
    { name: 'MORTOL: OPEN-TOMB allowed; clear all world 3 levels', types: ['mortol', 'hard'] },
    { name: 'MOONCAT: Obtain the Green or Yellow egg', types: ['mooncat', 'hard'] },
    { name: 'MOONCAT: Gold disk', types: ['mooncat', 'hard'] },
    { name: 'CAMOUFLAGE: Escape with 3/3 collectibles on 5 levels', types: ['camouflage', 'hard'] },
    {
      name: 'CAMOUFLAGE: Escape with 2/3 collectibles or more on 7 levels',
      types: ['camouflage', 'hard'],
    },
    { name: 'THE BIG BELL RACE: Reach 45+ points', types: ['thebigbellrace', 'hard'] },
    {
      name: 'THE BIG BELL RACE: Give 3 opponents a lap headstart and win on 3 separate tracks',
      types: ['thebigbellrace', 'hard'],
    },
    { name: 'OVERBOLD: Gold disk', types: ['overbold', 'hard'] },
    { name: 'OVERBOLD: Clear a round with maximum stakes', types: ['overbold', 'hard'] },
    {
      name: 'HYPER CONTENDER: Win 3 fights in a row on Hyper difficulty on default ring settings',
      types: ['hypercontender', 'hard'],
    },
    { name: 'HYPER CONTENDER: Gold disk', types: ['hypercontender', 'hard'] },
    { name: 'LORDS OF DISKONIA: Have 5 enemy disks drown', types: ['lordsofdiskonia', 'hard'] },
    {
      name: 'LORDS OF DISKONIA: Win a battle in a Full War on Commander difficulty',
      types: ['lordsofdiskonia', 'hard'],
    },
    { name: 'QUIBBLE RACE: Gold disk', types: ['quibblerace', 'hard'] },
    {
      name: 'QUIBBLE RACE: Win 3 bets on Quibbles with a 5:1 or higher payout',
      types: ['quibblerace', 'hard'],
    },
  ],
  [
    { name: 'NINPEK: Collect 3 crowns', types: ['ninpek', 'hard'] },
    { name: 'NINPEK: Score 18,000+ points', types: ['ninpek', 'hard'] },
    { name: 'MAGIC GARDEN: Obtain a score multiplier of 8x', types: ['magicgarden', 'hard'] },
    { name: 'MAGIC GARDEN: Gold disk', types: ['magicgarden', 'hard'] },
    {
      name: 'AVIANOS: Win a custom Fledgling game with a blessing from each ancestor (change no other settings)',
      types: ['avianos', 'hard'],
    },
    {
      name: 'AVIANOS: Win a custom Fledgling game with scrambled Ancestors (change no other settings)',
      types: ['avianos', 'hard'],
    },
    { name: 'GOLFARIA: Rescue 2 green balls', types: ['golfaria', 'hard'] },
    { name: 'GOLFARIA: Obtain the Brakes', types: ['golfaria', 'hard'] },
    {
      name: 'ONION DELIVERY: Hit 6 time boxes in one day and complete the day',
      types: ['oniondelivery', 'hard'],
    },
    {
      name: 'ONION DELIVERY: Complete 4 days in a run with 7+ deliveries each',
      types: ['oniondelivery', 'hard'],
    },
    { name: 'HOT FOOT: Get 3 blowouts in one tournament', types: ['hotfoot', 'hard'] },
    { name: 'HOT FOOT: Get 3 blowouts in one tournament', types: ['hotfoot', 'hard'] },
    { name: 'VAINGER: Collect the Multi Mod from Latom Sector', types: ['vainger', 'hard'] },
    { name: 'VAINGER: Obtain the Force Mod from Verde Sector', types: ['vainger', 'hard'] },
    { name: 'VALBRACE: Collect the zweihander', types: ['valbrace', 'hard'] },
    { name: 'VALBRACE: Solve 2 gem puzzles', types: ['valbrace', 'hard'] },
  ],
  [
    { name: 'VELGRESS: Gold disk', types: ['velgress', 'hard'] },
    { name: 'VELGRESS: Collect all 3 keys in a single run', types: ['velgress', 'hard'] },
    { name: 'PLANET ZOLDATH: Collect the dungeon Map Piece', types: ['planetzoldath', 'hard'] },
    { name: 'PLANET ZOLDATH: Collect the trade Map Piece', types: ['planetzoldath', 'hard'] },
    { name: 'CAMPANELLA: Have 25 lives', types: ['campanella', 'hard'] },
    {
      name: 'CAMPANELLA: Finish Stage C only earning points from bosses and bonus stages',
      types: ['campanella', 'hard'],
    },
    { name: 'PORGY: Defeat a boss', types: ['porgy', 'hard'] },
    { name: 'PORGY: Return 4 fish eggs to their mother', types: ['porgy', 'hard'] },
    { name: 'DIVERS: Obtain any Lance weapon', types: ['divers', 'hard'] },
    { name: 'DIVERS: Pull 2 levers', types: ['divers', 'hard'] },
    {
      name: 'STAR WASPIR: Clear waves 1 and 2 without using powerups (EEE, GGG, or GEE)',
      types: ['starwaspir', 'hard'],
    },
    {
      name: 'STAR WASPIR: As Red, have 3 bombs stored and 3 UFOs on screen at once in wave 2 or later',
      types: ['starwaspir', 'hard'],
    },
    { name: 'GRIMSTONE: Reach Level 4 with any character', types: ['grimstone', 'hard'] },
    {
      name: 'GRIMSTONE: Have 4 items equipped to everyone in a posse of 4',
      types: ['grimstone', 'hard'],
    },
    {
      name: 'CYBER OWLS: Have 2000 total points at HQ without playing Congo',
      types: ['cyberowls', 'hard'],
    },
    { name: 'CYBER OWLS: Clear Moscow with 1200+ score', types: ['cyberowls', 'hard'] },
  ],
  [
    {
      name: 'BUSHIDO BALL: Win the first match as every character',
      types: ['bushidoball', 'hard'],
    },
    {
      name: 'BUSHIDO BALL: Win the first match as every character',
      types: ['bushidoball', 'hard'],
    },
    { name: 'ATTACTICS: Score 1000+ points in Survival Mode', types: ['attactics', 'hard'] },
    { name: 'ATTACTICS: Use SLOW-DOWN; win a rank 160 battle', types: ['attactics', 'hard'] },
    { name: 'KICK CLUB: Have 5 extra lives at once', types: ['kickclub', 'hard'] },
    {
      name: 'KICK CLUB: Defeat the Goalie, then the Net in Ice World',
      types: ['kickclub', 'hard'],
    },
    {
      name: 'BLOCK KOALA: WORM-1234 allowed; beat 5 southeastern levels (15-27)',
      types: ['blockkoala', 'hard'],
    },
    { name: 'BLOCK KOALA: WORM-1234 allowed; beat level 14', types: ['blockkoala', 'hard'] },
    { name: 'WARPTANK: Collect 5 coffees', types: ['warptank', 'hard'] },
    {
      name: 'WARPTANK: SLIM-TANK allowed; beat Riot and Soft Sectors',
      types: ['warptank', 'hard'],
    },
    { name: 'MORTOL II: Collect 10 keys', types: ['mortolii', 'hard'] },
    {
      name: 'MORTOL II: Defeat all three mini bosses without using the Bomber',
      types: ['mortolii', 'hard'],
    },
    { name: 'ELFAZAR’S HAT: Clear Stage 3 (Frostin Town)', types: ['elfazarshat', 'hard'] },
    { name: 'ELFAZAR’S HAT: Collect 6 tickets in a run', types: ['elfazarshat', 'hard'] },
    { name: 'PILOT QUEST: Activate 2 teleporters', types: ['pilotquest', 'hard'] },
    { name: 'PILOT QUEST: Obtain the Blaster', types: ['pilotquest', 'hard'] },
    { name: 'CAMPANELLA 3: Clear all Stage B waves 0%', types: ['campanella3', 'hard'] },
    { name: 'CAMPANELLA 3: Beat Joe Pulp (Stage C Boss)', types: ['campanella3', 'hard'] },
  ],
  [
    {
      name: 'PARTY HOUSE: Use VIPS-ONLY; enter your Bingosync seed and win',
      types: ['partyhouse', 'hard'],
    },
    { name: 'PARTY HOUSE: Have 6 star guests in a party at once', types: ['partyhouse', 'hard'] },
    {
      name: 'RAIL HEIST: LAZY-COPS allowed; beat Vengeance! and The Final Score',
      types: ['railheist', 'hard'],
    },
    { name: 'RAIL HEIST: Collect all 3 stars on 3 different levels', types: ['railheist', 'hard'] },
    {
      name: 'ROCK ON! ISLAND: CLUB-PASS allowed; survive the first 5 waves of The Four Emperors w/o losing health',
      types: ['rockonisland', 'hard'],
    },
    {
      name: 'ROCK ON! ISLAND: CLUB-PASS allowed; beat Wasteland without chickens',
      types: ['rockonisland', 'hard'],
    },
    { name: 'PINGOLF: Hole-in-one on 3 different courses', types: ['pingolf', 'hard'] },
    { name: 'PINGOLF: Score -2 or better on 3 different courses', types: ['pingolf', 'hard'] },
    { name: 'CAMPANELLA 2: Clear Moire Woods II or Rink II', types: ['campanella2', 'hard'] },
    { name: 'CAMPANELLA 2: Collect two scrolls in one run', types: ['campanella2', 'hard'] },
    { name: 'RAKSHASA: Revive yourself 6 times in one run', types: ['rakshasa', 'hard'] },
    { name: 'RAKSHASA: Score 25,000 points', types: ['rakshasa', 'hard'] },
    { name: 'MINI & MAX: Collect a big shiny', types: ['miniandmax', 'hard'] },
    {
      name: 'MINI & MAX: Collect 150 shinies without obtaining the Shrink Potion',
      types: ['miniandmax', 'hard'],
    },
    { name: 'COMBATANTS: Slay a spider', types: ['combatants', 'hard'] },
    {
      name: 'COMBATANTS: ANTS-ANTS allowed; beat ‘Commando’ and ‘Commando2’',
      types: ['combatants', 'hard'],
    },
  ],
  [
    { name: 'BARBUTA: Fill all 8 item slots', types: ['barbuta', 'veryhard'] },
    { name: 'NINPEK: Use HARD-LOOP; reach a score of 22,000+', types: ['ninpek', 'veryhard'] },
    { name: 'MAGIC GARDEN: Win with a score of 50,000+', types: ['magicgarden', 'veryhard'] },
    {
      name: 'MORTOL: Use BENS-MODE; beat 2-B with 80+ lives remaining',
      types: ['mortol', 'veryhard'],
    },
    {
      name: 'PLANET ZOLDATH: Use TROT-TERS; enter your Bingosync seed and win',
      types: ['planetzoldath', 'veryhard'],
    },
    { name: 'ATTACTICS: Reach Lord (100+) in Ranked Mode', types: ['attactics', 'veryhard'] },
    { name: 'KICK CLUB: Gold disk', types: ['kickclub', 'veryhard'] },
    { name: 'AVIANOS: Gold disk', types: ['avianos', 'veryhard'] },
    { name: 'MOONCAT: Find 2 of 3 eggs', types: ['mooncat', 'veryhard'] },
    {
      name: 'BLOCK KOALA: WORM-1234 allowed; beat any 9 story levels',
      types: ['blockkoala', 'veryhard'],
    },
    { name: 'CAMOUFLAGE: Reach 70% completion or more', types: ['camouflage', 'veryhard'] },
    { name: 'GOLFARIA: Achieve 25% Completion', types: ['golfaria', 'veryhard'] },
    { name: 'THE BIG BELL RACE: Gold disk with no deaths', types: ['thebigbellrace', 'veryhard'] },
    { name: 'PORGY: Achieve 20% Completion', types: ['porgy', 'veryhard'] },
    { name: 'ONION DELIVERY: Gold disk', types: ['oniondelivery', 'veryhard'] },
    { name: 'PARTY HOUSE: Beat 2 random scenarios in a row', types: ['partyhouse', 'veryhard'] },
    { name: 'HOT FOOT: Gold disk without Edgar or July', types: ['hotfoot', 'veryhard'] },
    { name: 'DIVERS: Win a fight against Piranhas', types: ['divers', 'veryhard'] },
    { name: 'VAINGER: Achieve 25% Completion', types: ['vainger', 'veryhard'] },
    { name: 'VALBRACE: Defeat the Phantom Knight on Floor 2', types: ['valbrace', 'veryhard'] },
    {
      name: 'GRIMSTONE: With a posse of 4, see 1500 teeth in your bank account',
      types: ['grimstone', 'veryhard'],
    },
    {
      name: 'ELFAZAR’S HAT: Defeat Elfazar in Stage 4 (Grand Palace)',
      types: ['elfazarshat', 'veryhard'],
    },
    {
      name: 'PILOT QUEST: Return a ship part to the crash site',
      types: ['pilotquest', 'veryhard'],
    },
    { name: 'SEASIDE DRIVE: Gold disk', types: ['seasidedrive', 'veryhard'] },
  ],
  [
    { name: 'BUG HUNTER: Gold disk', types: ['bughunter', 'veryhard'] },
    { name: 'PAINT CHASE: Reach a score of 350+', types: ['paintchase', 'veryhard'] },
    {
      name: 'VELGRESS: Cherry disk without Upgrades or Jump Pads',
      types: ['velgress', 'veryhard'],
    },
    { name: 'DEVILITION: Gold disk', types: ['devilition', 'veryhard'] },
    { name: 'BUSHIDO BALL: Gold disk w/ Default Options', types: ['bushidoball', 'veryhard'] },
    { name: 'CAMPANELLA: Gold disk', types: ['campanella', 'veryhard'] },
    { name: 'WARPTANK: Beat any 9 sectors and speak to 3 NPCs', types: ['warptank', 'veryhard'] },
    {
      name: 'WALDORF’S JOURNEY: Enter the palace with 6 Puffins',
      types: ['waldorfsjourney', 'veryhard'],
    },
    { name: 'CARAMEL CARAMEL: Gold disk', types: ['caramelcaramel', 'veryhard'] },
    { name: 'RAIL HEIST: Collect 9 Devil Stars', types: ['railheist', 'veryhard'] },
    {
      name: 'ROCK ON! ISLAND: CLUB-PASS allowed; perfect two levels that aren’t Initial Encounter',
      types: ['rockonisland', 'veryhard'],
    },
    {
      name: 'PINGOLF: Cherry disk without going over par on more than two holes',
      types: ['pingolf', 'veryhard'],
    },
    {
      name: 'MORTOL II: Activate all three switches without ever using Scout',
      types: ['mortolii', 'veryhard'],
    },
    { name: 'FIST HELL: Clear the 4th scare', types: ['fisthell', 'veryhard'] },
    { name: 'OVERBOLD: Cherry Disk', types: ['overbold', 'veryhard'] },
    {
      name: 'CAMPANELLA 2: Obtain 6 power-up items in one run (square icons on left of screen)',
      types: ['campanella2', 'veryhard'],
    },
    {
      name: 'HYPER CONTENDER: Gold disk on Hard Difficulty',
      types: ['hypercontender', 'veryhard'],
    },
    { name: 'RAKSHASA: Gold disk', types: ['rakshasa', 'veryhard'] },
    { name: 'STAR WASPIR: Clear wave 3', types: ['starwaspir', 'veryhard'] },
    {
      name: 'LORDS OF DISKONIA: Win a Full War on Knight Difficulty',
      types: ['lordsofdiskonia', 'veryhard'],
    },
    { name: 'NIGHT MANOR: Cherry disk', types: ['nightmanor', 'veryhard'] },
    { name: 'MINI & MAX: Collect 350 shinies', types: ['miniandmax', 'veryhard'] },
    { name: 'COMBATANTS: ANTS-ANTS allowed; beat ‘This Is It’', types: ['combatants', 'veryhard'] },
    {
      name: 'CAMPANELLA 3: Reach Eggsaber without firing sideways',
      types: ['campanella3', 'veryhard'],
    },
    { name: 'CYBER OWLS: HAWK-BASE allowed; beat Antarctica', types: ['cyberowls', 'veryhard'] },
  ],
  [
    { name: 'Collect 4 gifts from games on this card', types: ['general', 'general'] },
    { name: 'Collect 6 gifts from games on this card', types: ['general', 'general'] },
    { name: 'Collect 8 gifts from games on this card', types: ['general', 'general'] },
    { name: 'Enter a top 5 score on 4 arcade leaderboards', types: ['general', 'general'] },
    { name: 'Enter a top 3 score on 2 arcade leaderboards', types: ['general', 'general'] },
    { name: 'Enter a top 3 score on 3 arcade leaderboards', types: ['general', 'general'] },
  ],
  [
    { name: 'Collect 3 gold disks from games on this card', types: ['general', 'general'] },
    { name: 'Collect 4 gold disks from games on this card', types: ['general', 'general'] },
    { name: 'Collect 5 gold disks from games on this card', types: ['general', 'general'] },
    { name: 'Collect 2 cherry disks from games on this card', types: ['general', 'general'] },
    { name: 'Collect 3 cherry disks from games on this card', types: ['general', 'general'] },
    { name: 'Collect 4 cherry disks from games on this card', types: ['general', 'general'] },
  ],
  [
    { name: 'Buy an item from a shop in 10 games', types: ['general', 'general'] },
    { name: 'Find an easter egg UFO in 5 games', types: ['general', 'general'] },
    { name: 'Find an egg in 10 games', types: ['general', 'general'] },
    { name: 'Increase your base HP in 6 games', types: ['general', 'general'] },
    { name: 'Collect a food item in 8 games', types: ['general', 'general'] },
    { name: 'Collect a beverage in 6 games', types: ['general', 'general'] },
    { name: 'Open 2 chests in 5 games', types: ['general', 'general'] },
    { name: 'Earn an extra life/1UP in 8 games', types: ['general', 'general'] },
    { name: 'Collect a key in 7 games', types: ['general', 'general'] },
  ],
  [
    { name: 'Defeat 7 bosses', types: ['general', 'general'] },
    { name: 'Defeat 2 bosses in 4 different games', types: ['general', 'general'] },
    { name: 'Defeat a boss in 6 different games', types: ['general', 'general'] },
    { name: 'Beat 2 levels in 8 different games', types: ['general', 'general'] },
    { name: 'Beat 4 levels in 5 different games', types: ['general', 'general'] },
    { name: 'Beat 8 levels in 3 different games', types: ['general', 'general'] },
  ],
  [
    {
      name: 'PILOT PARTY: Collect 4 gifts: Campanella 1/2/3, Planet Zoldath, Pilot Quest, The Big Bell Race',
      types: ['general', 'general'],
    },
    {
      name: 'ALPHA TRILOGY: Gold Velgress, Overbold, and Quibble Race as Alpha',
      types: ['general', 'general'],
    },
    { name: 'TRIATHLON: Gold Disk any 3 of the 5 “SPORT” games', types: ['general', 'general'] },
    { name: 'ARCADE ACE: Gold Disk any 3 of the 16 “ARCADE” games', types: ['general', 'general'] },
    {
      name: 'METROIDVANIA: Collect Abilities: 3 in Porgy, 2 in Vainger, 1 in Golfaria',
      types: ['general', 'general'],
    },
    {
      name: 'PUZZLER: Beat 5 levels in Block Koala, Camouflage, Warptank',
      types: ['general', 'general'],
    },
    {
      name: 'ROLE-PLAYER: Level up all your characters twice in Divers, Valbrace, Grimstone',
      types: ['general', 'general'],
    },
    {
      name: 'WAR IS BAD: Win 3 battles in Attactics, Avianos, Combatants',
      types: ['general', 'general'],
    },
    {
      name: 'AMY: Playing as Amy, beat 1 level in Party House, 2 in Hot Foot, 2 in Fist Hell',
      types: ['general', 'general'],
    },
    {
      name: 'DAY JOB: Beat 1 level in Bug Hunter, 2 in Onion Delivery, 3 in Rail Heist',
      types: ['general', 'general'],
    },
    {
      name: 'CAMPANELLA TRILOGY: Beat two worlds in Campanella, two in Campanella 2, one in Campanella 3',
      types: ['general', 'general'],
    },
    {
      name: 'RACER: Win 4 races in Paint Chase, The Big Bell Race, Quibble Race',
      types: ['general', 'general'],
    },
  ],
] as const;


